const WORDS = [
    // 2 âm tiết (30)
    "học sinh",
    "gia đình",
    "đất nước",
    "mặt trời",
    "mặt trăng",
    "ngôi sao",
    "bầu trời",
    "dòng sông",
    "ngọn núi",
    "cánh đồng",
    "biển cả",
    "thành phố",
    "nông thôn",
    "bệnh viện",
    "trường học",
    "xe cộ",
    "cơm nước",
    "sách vở",
    "bút mực",
    "hoa quả",
    "cây cối",
    "chim muông",
    "cá tôm",
    "bạn bè",
    "con người",
    "quê hương",
    "tương lai",
    "phở bò",
    "bánh mì",
    "cơm tấm",
    // 3 âm tiết (30)
    "nhà vệ sinh",
    "cây bút chì",
    "con cá sấu",
    "quả dưa hấu",
    "con chuồn chuồn",
    "anh chị em",
    "ông bà nội",
    "ông bà ngoại",
    "máy vi tính",
    "đèn giao thông",
    "hoa hướng dương",
    "quả măng cụt",
    "cây xương rồng",
    "hoa phong lan",
    "bún bò huế",
    "chim cánh cụt",
    "con gấu trúc",
    "con tê giác",
    "con sư tử",
    "con cá ngựa",
    "phim hoạt hình",
    "máy bay giấy",
    "hoa cẩm chướng",
    "chả lá lốt",
    "bún thịt nướng",
    "cà phê trứng",
    "bánh trôi nước",
    "bắp rang bơ",
    "bánh đa cua",
    "bánh bột lọc",
    // 4 âm tiết (30)
    "uống nước nhớ nguồn",
    "có chí thì nên",
    "ở hiền gặp lành",
    "ác giả ác báo",
    "gieo gió gặt bão",
    "nước chảy đá mòn",
    "tích tiểu thành đại",
    "trọng nghĩa khinh tài",
    "bút sa gà chết",
    "há miệng chờ sung",
    "nhất cử lưỡng tiện",
    "đồng cam cộng khổ",
    "vạn sự như ý",
    "bách chiến bách thắng",
    "mưa dầm thấm lâu",
    "gần mực thì đen",
    "chín bỏ làm mười",
    "phi thương bất phú",
    "họa vô đơn chí",
    "được voi đòi tiên",
    "máu chảy ruột mềm",
    "long tranh hổ đấu",
    "vong ân bội nghĩa",
    "trà sữa trân châu",
    "bún đậu mắm tôm",
    "lẩu thái chua cay",
    "cơm chiên dương châu",
    "cơm gà hải nam",
    "bò xào lá lốt",
    "bún bò nam bộ",
    "cà phê sữa đá",
    // 5 âm tiết (30)
    "lá lành đùm lá rách",
    "trời sinh voi sinh cỏ",
    "phú quý sinh lễ nghĩa",
    "bần cùng sinh đạo tặc",
    "cần cù bù thông minh",
    "học đi đôi với hành",
    "yêu cho roi cho vọt",
    "trâu chậm uống nước đục",
    "lương y như từ mẫu",
    "cái khó ló cái khôn",
    "gừng càng già càng cay",
    "hổ phụ sinh hổ tử",
    "phép vua thua lệ làng",
    "nước đến chân mới nhảy",
    "thời gian là vàng bạc",
    "vạn sự khởi đầu nan",
    "phòng bệnh hơn chữa bệnh",
    "cơm tấm sườn bì chả",
    "trứng cút lộn xào me",
    "bánh tráng cuốn thịt heo",
].map((phrase) => phrase.split(" "));
