const WORDS = [
    ["máy", "tính"],
    ["học", "sinh"],
    ["bệnh", "viện"],
    ["xe", "đạp"],
    ["bánh", "mì"],
    ["con", "mèo"],
    ["cửa", "hàng"],
    ["bầu", "trời"],
    ["mặt", "trăng"],
    ["hoa", "hồng"],
    ["cái", "bàn"],
    ["quyển", "sách"],
    ["thầy", "giáo"],
    ["dòng", "sông"],
    ["ngôi", "nhà"],
    ["nhà", "vệ", "sinh"],
    ["máy", "bay", "giấy"],
    ["con", "cá", "sấu"],
    ["anh", "chị", "em"],
    ["ông", "bà", "ngoại"],
    ["cây", "bút", "chì"],
    ["quả", "dưa", "hấu"],
    ["con", "chuồn", "chuồn"],
    ["xe", "đạp", "điện"],
    ["máy", "vi", "tính"],
    ["ông", "mặt", "trời"],
    ["con", "cá", "vàng"],
    ["chim", "bồ", "câu"],
    // 4 âm tiết
    ["uống", "nước", "nhớ", "nguồn"],
    ["có", "chí", "thì", "nên"],
    ["ở", "hiền", "gặp", "lành"],
    ["ác", "giả", "ác", "báo"],
    ["gieo", "gió", "gặt", "bão"],
    ["nước", "chảy", "đá", "mòn"],
    ["tích", "tiểu", "thành", "đại"],
    ["trọng", "nghĩa", "khinh", "tài"],
    // 5 âm tiết
    ["lá", "lành", "đùm", "lá", "rách"],
    ["trời", "sinh", "voi", "sinh", "cỏ"],
    ["phú", "quý", "sinh", "lễ", "nghĩa"],
    ["bần", "cùng", "sinh", "đạo", "tặc"],
    ["cần", "cù", "bù", "thông", "minh"],
    ["học", "đi", "đôi", "với", "hành"],
    // 6 âm tiết
    ["ăn", "quả", "nhớ", "kẻ", "trồng", "cây"],
    ["thương", "người", "như", "thể", "thương", "thân"],
    ["học", "thầy", "không", "tày", "học", "bạn"],
    ["lời", "nói", "chẳng", "mất", "tiền", "mua"],
    ["đói", "cho", "sạch", "rách", "cho", "thơm"],
    ["tốt", "gỗ", "hơn", "tốt", "nước", "sơn"],
    ["trăm", "hay", "không", "bằng", "tay", "quen"],
    ["một", "cây", "làm", "chẳng", "nên", "non"],
    ["anh", "em", "như", "thể", "tay", "chân"],
    ["miệng", "nam", "mô", "lòng", "dao", "kiếm"],
    ["yêu", "nhau", "củ", "ấu", "cũng", "tròn"],
    ["công", "cha", "như", "núi", "thái", "sơn"],
    ["thương", "nhau", "lắm", "cắn", "nhau", "đau"],
    ["nói", "thì", "dễ", "làm", "thì", "khó"],
    ["trẻ", "cậy", "cha", "già", "cậy", "con"],
    // 7 âm tiết
    ["kiến", "tha", "lâu", "ngày", "cũng", "đầy", "tổ"],
    ["một", "con", "sâu", "làm", "rầu", "nồi", "canh"],
    ["trăm", "nghe", "không", "bằng", "một", "lần", "thấy"],
];
